# Generated by Django 4.0.4 on 2026-04-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_alter_genre_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"ordering": ["last_name", "first_name"]},
        ),
    ]
